/**
 * API Types - Generated from OpenAPI Spec
 *
 * AUTO-GENERATED by type-generator-agent from generated-docs/specs/api-spec.yaml
 * Do not edit manually - regenerate with /api-mock-refresh or re-run DESIGN.
 *
 * These types correspond to the `components/schemas` section of the OpenAPI spec.
 * The existing base types (APIError, APIRequestConfig, etc.) remain in api.ts.
 *
 * Note: DefaultResponse is defined in api.ts (template base type) and matches
 * the spec's components/schemas/DefaultResponse exactly — not re-exported here.
 */

// ---------------------------------------------------------------------------
// Payment Batch schemas
// ---------------------------------------------------------------------------

export interface PaymentBatchRead {
  Id?: number;
  CreatedDate?: string;
  Status?: string;
  Reference?: string;
  LastChangedUser?: string;
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionAmount?: number;
  TotalVat?: number;
}

export interface PaymentBatchReadList {
  PaymentBatchList?: PaymentBatchRead[];
}

// ---------------------------------------------------------------------------
// Payment schemas
// ---------------------------------------------------------------------------

export interface PaymentRead {
  Id?: number;
  Reference?: string;
  AgencyName?: string;
  ClaimDate?: string;
  AgentName?: string;
  LastChangedUser?: string;
  LastChangedDate?: string;
  AgentSurname?: string;
  BondAmount?: number;
  CommissionType?: string;
  GrantDate?: string;
  RegistrationDate?: string;
  Bank?: string;
  CommissionAmount?: number;
  VAT?: number;
  Status?: string;
  BatchId?: number;
}

export interface PaymentReadList {
  PaymentList?: PaymentRead[];
}

// ---------------------------------------------------------------------------
// Dashboard schemas
// ---------------------------------------------------------------------------

export interface PaymentStatusReportItem {
  Status?: string;
  PaymentCount?: number;
  TotalPaymentAmount?: number;
  CommissionType?: string;
  AgencyName?: string;
}

export interface ParkedPaymentsAgingReportItem {
  Range?: string;
  AgencyName?: string;
  PaymentCount?: number;
}

export interface PaymentsByAgencyReportItem {
  AgencyName?: string;
  PaymentCount?: number;
  TotalCommissionCount?: number;
  Vat?: number;
}

export interface PaymentsDashboardRead {
  PaymentStatusReport?: PaymentStatusReportItem[];
  ParkedPaymentsAgingReport?: ParkedPaymentsAgingReportItem[];
  TotalPaymentCountInLast14Days?: number;
  PaymentsByAgency?: PaymentsByAgencyReportItem[];
}

// ---------------------------------------------------------------------------
// Inline request body types (extracted from path operations)
// ---------------------------------------------------------------------------

/** Request body for POST /v1/payment-batches */
export interface CreatePaymentBatchRequest {
  PaymentIds?: number[];
}

/** Request body for PUT /v1/payments/park */
export interface ParkPaymentsRequest {
  PaymentIds?: number[];
}

/** Request body for PUT /v1/payments/unpark */
export interface UnparkPaymentsRequest {
  PaymentIds?: number[];
}

// ---------------------------------------------------------------------------
// Query parameter types (for typed endpoint helpers)
// ---------------------------------------------------------------------------

/**
 * Query parameters for GET /v1/payments.
 * Index signature included so the type is assignable to QueryParams.
 */
export type GetPaymentsParams = {
  ClaimDate?: string;
  AgencyName?: string;
  Status?: string;
  [key: string]: string | undefined;
};

/**
 * Query parameters for GET /v1/payment-batches.
 * Index signature included so the type is assignable to QueryParams.
 */
export type GetPaymentBatchesParams = {
  Reference?: string;
  AgencyName?: string;
  [key: string]: string | undefined;
};
